module: "stellar_eqtide"
tide_model: "cpl"
input_fix:
  "vpl.dStopTime":
    units: "u.Myr"
    true_value: 1000
    label: r"age [Myr]"
  "secondary.dTidalQ":
    units: "u.dex(u.dimensionless_unscaled)"
    true_value: 6.0
    label: r"$\rm \log\mathcal{Q}_2$"
  "primary.dObliquity":
    units: "u.deg"
    true_value: 0
    label: r"\rm $\varepsilon_{1,i}$ [deg]"
  "secondary.dObliquity":
    units: "u.deg"
    true_value: 0
    label: r"\rm $\varepsilon_{2,i}$ [deg]"
  "primary.dMass":
    units: "u.Msun"
    true_value: 1.0
    label: r"$\rm M_1 \,[M_{\odot}]$"
  "secondary.dMass":
    units: "u.Msun"
    true_value: 1.0
    label: r"$\rm M_2 \,[M_{\odot}]$"
input_var:
  "primary.dRotPeriod":
    units: "u.day"
    true_value: 0.5
    bounds: (0.1, 10.0)
    data: (None, None)
    label: r"$\rm P_{rot1,i}$ [d]"
  "secondary.dRotPeriod":
    units: "u.day"
    true_value: 0.5
    bounds: (0.1, 10.0)
    data: (None, None)
    label: r"$\rm P_{rot2,i}$ [d]"
  "secondary.dEcc": 
    units: "u.dimensionless_unscaled"
    true_value: 0.3
    bounds: (0.0, 0.5)
    data: (None, None)
    label: r"$e_i$"
  "secondary.dOrbPeriod":
    units: "u.day"
    true_value: 7.0
    bounds: (1.0, 12.0)
    data: (None, None)
    label: r"$\rm P_{orb,i}$ [d]"
  "primary.dTidalQ":
    units: "u.dex(u.dimensionless_unscaled)"
    true_value: 6.0
    bounds: (4.0, 12.0)
    data: (None, None)
    label: r"$\rm \log\mathcal{Q}$"
output:
  "final.primary.RotPer":
    units: "u.day"
    uncertainty: 0.01
    label: r"$\rm P_{rot1,f}$ [d]"
  "final.secondary.RotPer":
    units: "u.day"
    uncertainty: 0.01
    label: r"$\rm P_{rot2,f}$ [d]"
  "final.secondary.OrbPeriod":
    units: "u.day"
    uncertainty: 0.00001
    label: r"$\rm P_{orb,f}$ [d]"
  "final.secondary.Eccentricity":
    units: "u.dimensionless_unscaled"
    uncertainty: 0.001
    label: r"$e_f$"
