module: "eqtide"
tide_model: "ctl"
input_fix:
  "vpl.dStopTime":
    units: "u.Myr"
    true_value: 5000
    label: r"age [Myr]"
  "secondary.dTidalTau":
    units: "u.dex(u.s)"
    true_value: -1.0
    label: r"$\rm \log\tau_2$ [dex(s)]"
  "primary.dRadius":
    units: "u.Rsun"
    true_value: 1.0
    label: r"$\rm R_1 \,[R_{\odot}]$"
  "secondary.dRadius":
    units: "u.Rsun"
    true_value: 1.0
    label: r"$\rm R_2 \,[R_{\odot}]$"
  "secondary.dOrbPeriod":
    units: "u.day"
    true_value: 7.0
    label: r"$\rm P_{orb,i}$ [d]"
input_var:
  "primary.dMass":
    units: "u.Msun"
    true_value: 1.0
    bounds: (0.1, 1.1)
    data: (None, None)
    label: r"$\rm M_1 \,[M_{\odot}]$"
  "secondary.dMass":
    units: "u.Msun"
    true_value: 1.0
    bounds: (0.1, 1.1)
    data: (None, None)
    label: r"$\rm M_2 \,[M_{\odot}]$"
  "primary.dRotPeriod":
    units: "u.day"
    true_value: 0.5
    bounds: (0.1, 10.0)
    data: (None, None)
    label: r"$\rm P_{rot1,i}$ [d]"
  "secondary.dRotPeriod":
    units: "u.day"
    true_value: 0.5
    bounds: (0.1, 10.0)
    data: (None, None)
    label: r"$\rm P_{rot2,i}$ [d]"
  "secondary.dEcc": 
    units: "u.dimensionless_unscaled"
    true_value: 0.3
    bounds: (0.0, 0.5)
    data: (None, None)
    label: r"$e_i$"
  "primary.dTidalTau":
    units: "u.dex(u.s)"
    true_value: -1.0
    bounds: (-4.0, 1.0)
    data: (None, None)
    label: r"$\rm \log\tau$ [dex(s)]"
output:
  "final.primary.RotPer":
    units: "u.day"
    uncertainty: 0.4
    label: r"$\rm P_{rot1,f}$ [d]"
  "final.secondary.RotPer":
    units: "u.day"
    uncertainty: 0.4
    label: r"$\rm P_{rot2,f}$ [d]"
  "final.secondary.OrbPeriod":
    units: "u.day"
    uncertainty: 0.00001
    label: r"$\rm P_{orb,f}$ [d]"
  "final.secondary.Eccentricity":
    units: "u.dimensionless_unscaled"
    label: r"$e_f$"
    uncertainty: 0.1
  "final.primary.RotAngMom":
    units: "u.kg * u.m**2 / u.s"
    label: r"$\rm J_{rot1,f}$"
    uncertainty: None
  "final.secondary.RotAngMom":
    units: "u.kg * u.m**2 / u.s"
    label: r"$\rm J_{rot2,f}$"
    uncertainty: None
  "final.secondary.OrbAngMom":
    units: "u.kg * u.m**2 / u.s"
    label: r"$\rm J_{orb,f}$"
    uncertainty: None
