module: "stellar_eqtide"
tide_model: "ctl"
input_fix:
  "secondary.dTidalTau":
    units: "u.dex(u.s)"
    true_value: -1.0
    label: r"$\rm \log\tau_2$ [dex(s)]"
input_var:
  "vpl.dStopTime":
    units: "u.Myr"
    true_value: 100
    prior_bounds: (10, 1000)
    prior_data: (None, None)
    label: r"age [Gyr]"
  "primary.dMass":
    units: "u.Msun"
    true_value: 1.0
    prior_bounds: (0.6, 1.1)
    prior_data: (None, None)
    label: r"$\rm M_1 [M_{\odot}]$"
  "secondary.dMass":
    units: "u.Msun"
    true_value: 1.0
    prior_bounds: (0.6, 1.1)
    prior_data: (None, None)
    label: r"$\rm M_2 [M_{\odot}]$"
  "primary.dObliquity":
    units: "u.deg"
    true_value: 0
    prior_bounds: (0, 30)
    prior_data: (None, None)
    label: r"\rm $\varepsilon_1 [\deg]$"
  "secondary.dObliquity":
    units: "u.deg"
    true_value: 0
    prior_bounds: (0, 30)
    prior_data: (None, None)
    label: r"\rm $\varepsilon_2 [\deg]$"
  "primary.dRotPeriod":
    units: "u.day"
    true_value: 0.5
    prior_bounds: (0.1, 6.0)
    prior_data: (None, None)
    label: r"$\rm P_{rot1} [d]$"
  "secondary.dRotPeriod":
    units: "u.day"
    true_value: 0.5
    prior_bounds: (0.1, 6.0)
    prior_data: (None, None)
    label: r"$\rm P_{rot2} [d]$"
  "secondary.dEcc": 
    units: "u.dimensionless_unscaled"
    true_value: 0.3
    prior_bounds: (0.0, 0.5)
    prior_data: (None, None)
    label: r"$e$"
  "secondary.dOrbPeriod":
    units: "u.day"
    true_value: 7.0
    prior_bounds: (0.1, 12.0)
    prior_data: (None, None)
    label: r"$\rm P_{orb} [d]$"
  "primary.dTidalTau":
    units: "u.dex(u.s)"
    true_value: -1.0
    prior_bounds: (-4.0, 1.0)
    prior_data: (None, None)
    label: r"$\rm \log\tau_1$ [dex(s)]"
output:
  "final.primary.RotPer":
    units: "u.day"
    uncertainty: 0.4
  "final.secondary.RotPer":
    units: "u.day"
    uncertainty: 0.4
  "final.secondary.OrbPeriod":
    units: "u.day"
    uncertainty: 0.00001
  "final.secondary.Eccentricity":
    units: "u.dimensionless_unscaled"
    uncertainty: 0.1
  "final.primary.Radius":
    units: "u.Rsun"
    uncertainty: 0.01
  "final.secondary.Radius":
    units: "u.Rsun"
    uncertainty: 0.01
  "final.primary.Luminosity":
    units: "u.Lsun"
    uncertainty: 0.01
  "final.secondary.Luminosity":
    units: "u.Lsun"
    uncertainty: 0.01
  "final.primary.Temperature":
    units: "u.K"
    uncertainty: 50.0
  "final.secondary.Temperature":
    units: "u.K"
    uncertainty: 50.0
